### ISSUE TITLE
Android 2.2.x can't install: failed verification of META-INF/CERT.SF

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#234]
A user sent this log:

```
2014-11-11 15:04:53.581 D 172/PackageParser: Scanning package: /mnt/asec/smdl2tmp1/pkg.apk
2014-11-11 15:04:54.551 W 172/PackageParser: Exception reading assets/de/blackbox.html in /mnt/asec/smdl2tmp1/pkg.apk
java.lang.SecurityException: /mnt/asec/smdl2tmp1/pkg.apk failed verification of META-INF/CERT.SF
    at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:320)
    at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:272)
    at java.util.jar.JarFile.getInputStream(JarFile.java:392)
    at android.content.pm.PackageParser.loadCertificates(PackageParser.java:337)
    at android.content.pm.PackageParser.collectCertificates(PackageParser.java:508)
    at com.android.server.PackageManagerService.installPackageLI(PackageManagerService.java:5978)
    at com.android.server.PackageManagerService.access$2100(PackageManagerService.java:134)
    at com.android.server.PackageManagerService$5.run(PackageManagerService.java:4836)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:123)
    at android.os.HandlerThread.run(HandlerThread.java:60)
2014-11-11 15:04:54.551 E 172/PackageParser: Package name.boyle.chris.sgtpuzzles has no certificates at entry assets/de/blackbox.html; ignoring!
```

I can reproduce it on a 2.2 emulator, and not on 2.1 or 2.3, and it stopped working between 9561.1 and 10264.1.

At least strongly related to https://code.google.com/p/android/issues/detail?id=56006 - but in my case it's seemingly not what comment 19 and nearby discuss about dsaWithSHA1 versus dsaEncryption. This command gives identical output for CERT.DSA between the working/non-working APKs, and it contains dsaWithSHA1:

```
openssl pkcs7 -print_certs -text -inform DER -in CERT.DSA
```

**Comment by zvr** [comment]
The error seems to be triggered when parsing the `META-INF/CERT.SF` file, under the following conditions:
* it has *MainAttributes* section; and                                                                                                   
* it is not signed by *signtool*; and                                                                                                  
* there is no *-Digest-Manifest-Main-Attributes* attribute.                                                                              

Using *jarsigner* as described in http://developer.android.com/tools/publishing/app-signing.html produces a file where the two last conditions do not hold, and the package can be installed on (at least one) Android 2.2 device.

**Comment by chrisboyle** [comment]
Thanks. For reference all recent builds were signed with Android Studio (Build -> Generate Signed APK).

**Comment by chrisboyle** [comment]
I want to use current versions of the Support Library. As of August 2016, that unfortunately [requires `minSdkVersion` 9](https://developer.android.com/topic/libraries/support-library/index.html#api-versions). That makes 2.2 unsupported, and since I in any case never had any solid ideas for how to fix this issue without compromising support for newer versions of Android, I'm closing the ticket. Sorry I wasn't able to help more.
